#!/bin/bash
#
# cron_update.sh - Generate cron jobs for BTRFS snapshot scheduling
#
# Usage: cron_update.sh
#
# Reads all per-share configuration files and generates a cron file at
# /etc/cron.d/btrfs-snapshots with appropriate entries. Each cron entry
# runs snapshot_create.sh followed by snapshot_rotate.sh.
#
# Supported schedules (per-share SCHEDULE= config key):
#   every15min  - */15 * * * *
#   hourly      - 0 * * * *
#   every6hours - 0 */6 * * *
#   daily       - 0 2 * * *     (2:00 AM)
#   weekly      - 0 3 * * 0     (3:00 AM Sunday)
#   disabled    - no cron entry
#
# If the plugin is disabled globally, removes the cron file entirely.
#
# Exit codes:
#   0 - Success
#   1 - Configuration error
#

###############################################################################
# Configuration
###############################################################################

PLUGIN_NAME="btrfs-snapshots"
GLOBAL_CFG="/boot/config/plugins/${PLUGIN_NAME}/${PLUGIN_NAME}.cfg"
SHARE_CFG_DIR="/boot/config/plugins/${PLUGIN_NAME}/shares"
LOG_FILE="/var/log/${PLUGIN_NAME}.log"
CRON_FILE="/etc/cron.d/${PLUGIN_NAME}"
SCRIPTS_DIR="/usr/local/emhttp/plugins/${PLUGIN_NAME}/scripts"

# Defaults
PLUGIN_ENABLED="yes"

###############################################################################
# Logging
###############################################################################

log() {
    local level="$1"
    shift
    local msg="$*"
    local ts
    ts="$(date '+%Y-%m-%d %H:%M:%S')"
    echo "${ts} [${level}] [cron_update] ${msg}" >> "${LOG_FILE}"
    if [[ -t 1 ]]; then
        echo "${ts} [${level}] ${msg}"
    fi
}

###############################################################################
# Load Configuration
###############################################################################

load_config() {
    if [[ -f "${GLOBAL_CFG}" ]]; then
        # shellcheck source=/dev/null
        source "${GLOBAL_CFG}"
        PLUGIN_ENABLED="${PLUGIN_ENABLED:-yes}"
    fi
}

###############################################################################
# Discover Configured Shares
###############################################################################

get_configured_shares() {
    if [[ ! -d "${SHARE_CFG_DIR}" ]]; then
        return
    fi

    local cfg
    for cfg in "${SHARE_CFG_DIR}"/*.cfg; do
        [[ -f "$cfg" ]] || continue
        local name
        name="$(basename "${cfg}" .cfg)"
        echo "${name}"
    done
}

###############################################################################
# Schedule to Cron Expression
###############################################################################

# Converts a human-readable schedule name to a cron timing expression.
schedule_to_cron() {
    local schedule="$1"

    case "${schedule}" in
        every15min)
            echo "*/15 * * * *"
            ;;
        hourly)
            echo "0 * * * *"
            ;;
        every6hours)
            echo "0 */6 * * *"
            ;;
        daily)
            echo "0 2 * * *"
            ;;
        weekly)
            echo "0 3 * * 0"
            ;;
        disabled|"")
            echo ""
            ;;
        *)
            # Check if it's a raw cron expression (5 fields)
            if [[ "$schedule" =~ ^[0-9*/,-]+[[:space:]]+[0-9*/,-]+[[:space:]]+[0-9*/,-]+[[:space:]]+[0-9*/,-]+[[:space:]]+[0-9*/,-]+$ ]]; then
                echo "$schedule"
            else
                log "WARN" "Unknown schedule '${schedule}', treating as disabled"
                echo ""
            fi
            ;;
    esac
}

###############################################################################
# Generate Cron File
###############################################################################

generate_cron_file() {
    local shares
    shares="$(get_configured_shares)"

    if [[ -z "$shares" ]]; then
        log "INFO" "No configured shares, removing cron file"
        remove_cron_file
        return 0
    fi

    local entry_count=0
    local cron_content=""

    # File header
    cron_content+="# BTRFS Snapshots Plugin - Auto-generated cron jobs
# Do not edit manually - regenerated by cron_update.sh
# Last updated: $(date '+%Y-%m-%d %H:%M:%S')
#
# Format: minute hour day month weekday user command
SHELL=/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
"

    while IFS= read -r share; do
        [[ -z "$share" ]] && continue

        local cfg_file="${SHARE_CFG_DIR}/${share}.cfg"
        local share_enabled="yes"
        local schedule="disabled"

        if [[ -f "${cfg_file}" ]]; then
            # Reset variables before sourcing
            ENABLED="yes"
            SCHEDULE="disabled"

            # shellcheck source=/dev/null
            source "${cfg_file}"

            share_enabled="${ENABLED:-yes}"
            schedule="${SCHEDULE:-disabled}"
        fi

        # Skip disabled shares
        if [[ "${share_enabled}" != "yes" ]]; then
            cron_content+="# ${share}: disabled
"
            continue
        fi

        # Convert schedule to cron expression
        local cron_expr
        cron_expr="$(schedule_to_cron "${schedule}")"

        if [[ -z "${cron_expr}" ]]; then
            cron_content+="# ${share}: no schedule configured
"
            continue
        fi

        # Escape the share name for shell safety in the cron command
        # We already validated it with sanitize_name at config time,
        # but quote it in the cron entry for defense in depth.
        local safe_share="${share//\"/\\\"}"

        # Build the cron entry: create snapshot, then rotate
        # Run as root, redirect output to log
        cron_content+="# Share: ${share} (schedule: ${schedule})
${cron_expr} root ${SCRIPTS_DIR}/snapshot_create.sh \"${safe_share}\" scheduled >> ${LOG_FILE} 2>&1 && ${SCRIPTS_DIR}/snapshot_rotate.sh \"${safe_share}\" >> ${LOG_FILE} 2>&1
"

        ((entry_count++))
        log "INFO" "Cron entry for '${share}': ${cron_expr}"
    done <<< "${shares}"

    if [[ $entry_count -eq 0 ]]; then
        log "INFO" "No active cron entries, removing cron file"
        remove_cron_file
        return 0
    fi

    # Write the cron file
    echo "${cron_content}" > "${CRON_FILE}"

    # Cron files in /etc/cron.d must:
    # - Be owned by root
    # - Not be writable by group/other
    # - Not be executable
    chmod 644 "${CRON_FILE}" 2>/dev/null

    log "INFO" "Generated cron file with ${entry_count} entries at ${CRON_FILE}"
    echo "Cron updated: ${entry_count} scheduled shares"
    return 0
}

###############################################################################
# Remove Cron File
###############################################################################

remove_cron_file() {
    if [[ -f "${CRON_FILE}" ]]; then
        rm -f "${CRON_FILE}"
        log "INFO" "Removed cron file: ${CRON_FILE}"
        echo "Cron file removed"
    fi
}

###############################################################################
# Main
###############################################################################

main() {
    # Load configuration
    load_config

    # If plugin is disabled, remove cron file
    if [[ "${PLUGIN_ENABLED}" != "yes" ]]; then
        log "INFO" "Plugin is disabled, removing cron file"
        remove_cron_file
        exit 0
    fi

    # Generate cron entries
    generate_cron_file

    exit 0
}

main "$@"
